name: lims-puppeteer-service
region: nyc
services:
  - name: puppeteer-pdf
    source_dir: /puppeteer-service
    github:
      repo: dranandnandi/lims-11-9
      branch: bill-dr-location-b2b
      deploy_on_push: true
    build_command: npm install && npx puppeteer browsers install chrome && npm run build
    run_command: npm start
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
      - key: PUPPETEER_CACHE_DIR
        value: "/workspace/.cache/puppeteer"
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
